// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBerjgy4OmSzLAXgx9nJqfBZfY86QSKODM',
    appId: '1:842683482565:web:cd8c1cd4717b4281878bac',
    messagingSenderId: '842683482565',
    projectId: 'beatbox-music-app',
    authDomain: 'beatbox-music-app.firebaseapp.com',
    storageBucket: 'beatbox-music-app.appspot.com',
    measurementId: 'G-R2YFG94614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzbHcj0MMX_8nosYENIIN916pgqw44H4',
    appId: '1:842683482565:android:efec96a8ec83591b878bac',
    messagingSenderId: '842683482565',
    projectId: 'beatbox-music-app',
    storageBucket: 'beatbox-music-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkSt63rIQ_NijKY9oBTs6vtR5SllnqIM',
    appId: '1:842683482565:ios:f7e79cfe70eece99878bac',
    messagingSenderId: '842683482565',
    projectId: 'beatbox-music-app',
    storageBucket: 'beatbox-music-app.appspot.com',
    iosBundleId: 'com.example.beatBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkSt63rIQ_NijKY9oBTs6vtR5SllnqIM',
    appId: '1:842683482565:ios:7cd4410bd1a75d04878bac',
    messagingSenderId: '842683482565',
    projectId: 'beatbox-music-app',
    storageBucket: 'beatbox-music-app.appspot.com',
    iosBundleId: 'com.example.beatBox.RunnerTests',
  );
}
